name: spotify_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  video_player: ^2.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/liked_song.png
    - assets/images/cigarettes_after_sex.jpeg
    - assets/images/ndx_aka.jpeg
    - assets/images/didi.jpeg
    - assets/images/dj_virall.jpeg
    - assets/images/playlist_gondes.jpeg
    - assets/images/mgmt.jpeg
    - assets/images/galau_versi_jawa.jpeg
    - assets/images/live_events.jpg
    - assets/images/made_for_you.png
    - assets/images/music.jpeg
    - assets/images/podcasts.jpeg
    - assets/videos/satu_bulan.mp4

  uses-material-design: true
