name: spotify_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5  # Add this line for GetX package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/liked_song.png
    - assets/images/cigarettes_after_sex.jpeg
    - assets/images/ndx_aka.jpeg
    - assets/images/didi.jpeg
    - assets/images/dj_virall.jpeg
    - assets/images/playlist_gondes.jpeg
    - assets/images/mgmt.jpeg
    - assets/images/galau_versi_jawa.jpeg

  uses-material-design: true
